language: r
warnings_are_errors: true
sudo: required
env:
  global:
  - NOT_CRAN=true
  - secure: 6C8p9WCWfvVizUIvGKO/umjQKinYJQL8ETCuttmJ91s1WDO9XI4UMVl+vTg/LMfUaz8jiqOy0mVbvVgw49ESCXBIIF7H8FTdMN5Oe0csn2ruhxxxp7SqPravyXu2SrsjVcXHyskABKNOU79sWd/EIby6nLJs6RhMkbQgFsDh4BUNpRnjjZB8Z8opEfshNZYhnqX2Si/nvISSZS4MOEYAz34TPRS21oB7bJhnJgfRYLSSbRnx2TtF0qpErUp9Qt4Uyx83j/c5D48B6RdJx1aZh4XA/iVQGNISbjvK3uUdWnxzQo5pW+MXcW+LV3wLr1rUlp2ohl2TiG2hwqa+WAD9+45ZvbKXm85t0C+edYxaRUG2Zjd60I97kzTq3pPWT60VHdUujQcCBsBJAcWVPBSWcVStNrParOwJn1HooP2DVjaDtvdugLvv5EYOe1U4BlQifzif8xvXP92nTPH+pHGw3jc5sGV8lIgjzUgeVapBC/96hTQ7eL7REK1umBCiXrPm4LD/bdIevIBumr0uqbt3RC1reh0NKHyHVKNiCrGzsEZoxzYjA2jrxDwFmorTZlSTD857MZcvUCvh/5RAPVM1UGFweWzBmDgWlq7qIakfPQ+W69jVseTFBTJJGTqdXXwBXzeQ44HY9915bD74Z6AHvjDSBWcgRMeCzUzd1rxh2Xo=
before_install:
- echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
- chmod 755 ./.push_gh_pages.sh
after_success:
- ./.push_gh_pages.sh
r_binary_packages:
- dplyr
- tidyr
- knitr
r_github_packages:
- tidyverse/dplyr
- hadley/dbplyr
notifications:
  email:
    on_success: change
    on_failure: always
  slack: langcog:NOgyVdCqRrN5T7VCzmEy5pZT
