language: r
cache: packages
warnings_are_errors: true
sudo: required
env:
  global:
  - NOT_CRAN=true
  - secure: VB2LgmIYHl8whrUcpjxM6bI046i+HPYvCpBoNKfMwfpdmxSF6UaIUZyTwRrmE6kYvy/nU1YTh948U+SFh8OZVPo2BVRKJ3vREO58mIBqSp/U5+IsaLnwRHsJ74yvDw2WKFOpYvufLbQm/DOxakZXgek+o1WXuX1XNWmPKFTTjZv1xjFJsYgLsNbcgjeLvICReHEEWpmFKWxKEeSaBMQm9TdxCp2vOjhiwNvppSHVRKe1tt9H6hlV3MZtwYO3CX/11743NZwp4B+1USz+00IIk23CKKA2YiVnC+volWGWEMrLzJuyO1w+sHt0oRQMhSswM1lnFVtzoGC376LmwWSebuCXZ+hHOa/eH8+GMGWMZN49+44OW9kL2BzqHOz0u6eQm+xuDwPFrEE3xc05Rc5THzZuJCw737cNSBVL79nLli638/eNNXEeGcUWoVFMEyR73xLqX2I2O5l/EXyCc9q0MsQ6jwyC2mf0SzgazzzSp55oy1/thiDh2g/z1/zLMAWVpbKwiMq/p7YosVvrQUir/pbsW8+rs9ja7Q1DShdckOCEpG46n7HwYRB3CWi+4GGMJmL8MaScFqGEWhoc0cF/ifYWVRQxxLV/YRYGT1Y/cAnfR7Dk+b1UlZmrfhrNS48M9XQq7bx7F7FzC3UXBb4+Q3OjHpuutR8jPgXnCKZyXK0=
before_install:
- echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
- chmod 755 ./.push_gh_pages.sh
after_success:
- ./.push_gh_pages.sh
r_binary_packages:
- dplyr
- tidyr
- knitr
notifications:
  email:
    on_success: change
    on_failure: always
  slack: langcog:NOgyVdCqRrN5T7VCzmEy5pZT
